runCIPipeline(application: env.APP_NAME,
              agent: "maven",
              compileCommands: "mvn package -DskipTests -s settings.xml",
              testCommands: "mvn test -s settings.xml",
              artifactsDir: "./target")